name: readly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  iconsax: ^0.0.8
  tab_indicator_styler: ^2.0.0
  http: ^1.4.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  provider: ^6.1.5
  firebase_storage: ^13.0.0
  lottie: ^3.1.2
  flutter_slidable: ^4.0.0
  badges: ^3.1.2
  url_launcher: ^6.3.2
  gap: ^3.0.1
  firebase_auth: ^6.0.0
  loading_animation_widget: ^1.3.0
  path_provider: ^2.1.5
  epub_view: ^3.2.0
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.11.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
